services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - monitoring
      - proxy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
      - proxy

networks:
  monitoring:
    driver: bridge

  proxy:
    external: true
    name: reverse-proxy-lab_proxy

volumes:
  prometheus-data:
  grafana-data: